//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeData.SchoolServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NameStudent del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        ConsumeData.SchoolServiceReference.AddResponse Add(ConsumeData.SchoolServiceReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeData.SchoolServiceReference.AddResponse> AddAsync(ConsumeData.SchoolServiceReference.AddRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ReadAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAll", ReplyAction="*")]
        ConsumeData.SchoolServiceReference.ReadAllResponse ReadAll(ConsumeData.SchoolServiceReference.ReadAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeData.SchoolServiceReference.ReadAllResponse> ReadAllAsync(ConsumeData.SchoolServiceReference.ReadAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeData.SchoolServiceReference.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(ConsumeData.SchoolServiceReference.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdStudent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NameStudent;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(int IdStudent, string NameStudent) {
            this.IdStudent = IdStudent;
            this.NameStudent = NameStudent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeData.SchoolServiceReference.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(ConsumeData.SchoolServiceReference.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(string AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAll", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeData.SchoolServiceReference.ReadAllRequestBody Body;
        
        public ReadAllRequest() {
        }
        
        public ReadAllRequest(ConsumeData.SchoolServiceReference.ReadAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadAllRequestBody {
        
        public ReadAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeData.SchoolServiceReference.ReadAllResponseBody Body;
        
        public ReadAllResponse() {
        }
        
        public ReadAllResponse(ConsumeData.SchoolServiceReference.ReadAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadAllResult;
        
        public ReadAllResponseBody() {
        }
        
        public ReadAllResponseBody(string ReadAllResult) {
            this.ReadAllResult = ReadAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumeData.SchoolServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumeData.SchoolServiceReference.WebService1Soap>, ConsumeData.SchoolServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeData.SchoolServiceReference.AddResponse ConsumeData.SchoolServiceReference.WebService1Soap.Add(ConsumeData.SchoolServiceReference.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public string Add(int IdStudent, string NameStudent) {
            ConsumeData.SchoolServiceReference.AddRequest inValue = new ConsumeData.SchoolServiceReference.AddRequest();
            inValue.Body = new ConsumeData.SchoolServiceReference.AddRequestBody();
            inValue.Body.IdStudent = IdStudent;
            inValue.Body.NameStudent = NameStudent;
            ConsumeData.SchoolServiceReference.AddResponse retVal = ((ConsumeData.SchoolServiceReference.WebService1Soap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeData.SchoolServiceReference.AddResponse> ConsumeData.SchoolServiceReference.WebService1Soap.AddAsync(ConsumeData.SchoolServiceReference.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeData.SchoolServiceReference.AddResponse> AddAsync(int IdStudent, string NameStudent) {
            ConsumeData.SchoolServiceReference.AddRequest inValue = new ConsumeData.SchoolServiceReference.AddRequest();
            inValue.Body = new ConsumeData.SchoolServiceReference.AddRequestBody();
            inValue.Body.IdStudent = IdStudent;
            inValue.Body.NameStudent = NameStudent;
            return ((ConsumeData.SchoolServiceReference.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeData.SchoolServiceReference.ReadAllResponse ConsumeData.SchoolServiceReference.WebService1Soap.ReadAll(ConsumeData.SchoolServiceReference.ReadAllRequest request) {
            return base.Channel.ReadAll(request);
        }
        
        public string ReadAll() {
            ConsumeData.SchoolServiceReference.ReadAllRequest inValue = new ConsumeData.SchoolServiceReference.ReadAllRequest();
            inValue.Body = new ConsumeData.SchoolServiceReference.ReadAllRequestBody();
            ConsumeData.SchoolServiceReference.ReadAllResponse retVal = ((ConsumeData.SchoolServiceReference.WebService1Soap)(this)).ReadAll(inValue);
            return retVal.Body.ReadAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeData.SchoolServiceReference.ReadAllResponse> ConsumeData.SchoolServiceReference.WebService1Soap.ReadAllAsync(ConsumeData.SchoolServiceReference.ReadAllRequest request) {
            return base.Channel.ReadAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeData.SchoolServiceReference.ReadAllResponse> ReadAllAsync() {
            ConsumeData.SchoolServiceReference.ReadAllRequest inValue = new ConsumeData.SchoolServiceReference.ReadAllRequest();
            inValue.Body = new ConsumeData.SchoolServiceReference.ReadAllRequestBody();
            return ((ConsumeData.SchoolServiceReference.WebService1Soap)(this)).ReadAllAsync(inValue);
        }
    }
}
